[package]
name = "rustybrot-web"
version = "0.0.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]
description = ""
keywords = ["mandelbrot", "buddhabrot", "webassembly", "asmjs", "web"]
license = "MIT/Apache-2.0"

[dependencies.rustybrot-lib]
path = "../rustybrot-lib"